# Generated by Django 4.2.7 on 2025-02-01 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Primary phone number must be unique.",
                        max_length=30,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "second_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Optional secondary phone number for additional contact.",
                        max_length=30,
                        null=True,
                        region=None,
                        verbose_name="Secondary Phone Number",
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "about_me",
                    models.TextField(
                        default="Say something about yourself", verbose_name="About me"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        default="profile_default.png",
                        upload_to="",
                        verbose_name="Profile Photo",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="CD", max_length=180, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Lubumbashi", max_length=180, verbose_name="City"
                    ),
                ),
                (
                    "is_buyer",
                    models.BooleanField(
                        default=True,
                        help_text="Are you looking to Buy a Product",
                        verbose_name="Buyer",
                    ),
                ),
                (
                    "is_seller",
                    models.BooleanField(
                        default=False,
                        help_text="Are you looking to Sell a Product",
                        verbose_name="Seller",
                    ),
                ),
                (
                    "is_agent",
                    models.BooleanField(
                        default=False,
                        help_text="Are you an Agent?",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "num_reviews",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Number of Reviews",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KYC",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "government_id",
                    models.CharField(
                        blank=True,
                        help_text="Government-issued identification number (e.g., passport, national ID).",
                        max_length=50,
                        null=True,
                        verbose_name="Government ID",
                    ),
                ),
                (
                    "government_id_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image of your government-issued ID.",
                        null=True,
                        upload_to="kyc/government_ids/",
                        verbose_name="Government ID Image",
                    ),
                ),
                (
                    "proof_of_address",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a document that proves your address (e.g., utility bill, bank statement).",
                        null=True,
                        upload_to="kyc/proof_of_address/",
                        verbose_name="Proof of Address",
                    ),
                ),
                (
                    "kyc_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the user's KYC information has been verified.",
                        verbose_name="KYC Verified",
                    ),
                ),
                (
                    "kyc_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the user's KYC information was verified.",
                        null=True,
                        verbose_name="KYC Verified At",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        help_text="The profile associated with this KYC information.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
